//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarHub.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarHub.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Restaurante.
        /// </summary>
        internal static string AddRestaurantText {
            get {
                return ResourceManager.GetString("AddRestaurantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de Propietarios.
        /// </summary>
        internal static string AdminTitlePage {
            get {
                return ResourceManager.GetString("AdminTitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BarHub.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF.
        /// </summary>
        internal static string CifRestaurantText {
            get {
                return ResourceManager.GetString("CifRestaurantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ej: correodecontacto@ayuda.com.
        /// </summary>
        internal static string ContactEmailPlaceholder {
            get {
                return ResourceManager.GetString("ContactEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email de Contacto.
        /// </summary>
        internal static string ContactEmailText {
            get {
                return ResourceManager.GetString("ContactEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono de la persona de contacto.
        /// </summary>
        internal static string ContactPhonePlaceholder {
            get {
                return ResourceManager.GetString("ContactPhonePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono de Contacto.
        /// </summary>
        internal static string ContactPhoneText {
            get {
                return ResourceManager.GetString("ContactPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copyright © Todos los derechos reservados..
        /// </summary>
        internal static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Restaurante.
        /// </summary>
        internal static string CreateRestaurantText {
            get {
                return ResourceManager.GetString("CreateRestaurantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Logo.
        /// </summary>
        internal static string InsertLogoText {
            get {
                return ResourceManager.GetString("InsertLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string LogInText {
            get {
                return ResourceManager.GetString("LogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Restaurante.
        /// </summary>
        internal static string ModifyRestaurantText {
            get {
                return ResourceManager.GetString("ModifyRestaurantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Imagen.
        /// </summary>
        internal static string NoImageText {
            get {
                return ResourceManager.GetString("NoImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIF de la empresa....
        /// </summary>
        internal static string RestaurantCifPlaceholder {
            get {
                return ResourceManager.GetString("RestaurantCifPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logo del Restaurante.
        /// </summary>
        internal static string RestaurantLogoText {
            get {
                return ResourceManager.GetString("RestaurantLogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la empresa....
        /// </summary>
        internal static string RestaurantNamePlaceholder {
            get {
                return ResourceManager.GetString("RestaurantNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Restaurante.
        /// </summary>
        internal static string RestaurantNameText {
            get {
                return ResourceManager.GetString("RestaurantNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        internal static string SaveChangesText {
            get {
                return ResourceManager.GetString("SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una imagen.
        /// </summary>
        internal static string SelectImageText {
            get {
                return ResourceManager.GetString("SelectImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantener iniciada la sesion.
        /// </summary>
        internal static string StayLoggedIn {
            get {
                return ResourceManager.GetString("StayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a www.davpicroc.es.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
